# This file was generated by GoReleaser. DO NOT EDIT.
cask "opensource" do
  version "3.0.1"

  on_macos do
    on_arm do
      sha256 "3baa28cad27355e37f630de07f086b793cc00997b85fc43e5052d07e77254cd6"
      url "https://github.com/mohnish/opensource/releases/download/#{version}/opensource_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2fdb7b878cbbfbfb3ca5888434cbae7f92d28ca56ad1981a95fb541427a4cd80"
      url "https://github.com/mohnish/opensource/releases/download/#{version}/opensource_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7cbc82ad9d03cccf0ce6c51331f42b83b686c58a28e078b4f2e1df483d118939"
      url "https://github.com/mohnish/opensource/releases/download/#{version}/opensource_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6f21f21cebc4cb6d6e1428fbbc68e337c18bbf67cb7115aa2cd40a0d33e6916b"
      url "https://github.com/mohnish/opensource/releases/download/#{version}/opensource_#{version}_linux_amd64.tar.gz"
    end
  end

  name "opensource"
  desc "Command line tool that adds an open source license to your project"
  homepage "https://github.com/mohnish/opensource"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opensource"

  # No zap stanza required
end
