# This file was generated by GoReleaser. DO NOT EDIT.
cask "opensource" do
  version "3.0.2"

  on_macos do
    on_arm do
      sha256 "9eb08a91c92a27deafba3e5cffe3eb9522dc534ea106fdccf74720ac95206fbf"
      url "https://github.com/mohnish/opensource/releases/download/#{version}/opensource_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4fa4f403943b61a6669c679c2042cbd5b7bb3c6f7912f46e7f7ed2f6d8592b0b"
      url "https://github.com/mohnish/opensource/releases/download/#{version}/opensource_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1d56db55aa3d6e5db13e81ab1fae516668ca3eb97b35dac2f8c73c73bd4b5541"
      url "https://github.com/mohnish/opensource/releases/download/#{version}/opensource_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "481d8b80cae24c69aab3348fdfd743e2f7a0d2673cf1cc3a8ad8a24da615b22b"
      url "https://github.com/mohnish/opensource/releases/download/#{version}/opensource_#{version}_linux_amd64.tar.gz"
    end
  end

  name "opensource"
  desc "Command line tool that adds an open source license to your project"
  homepage "https://github.com/mohnish/opensource"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "opensource"

  # No zap stanza required
end
